Repository appKom/penne, pull requests merged in 2024-10, with the labels that each got.

#76 75 setup db for admin dashboard
  .env.local.template
  .env.template
  .gitignore
  README.md
  app/admin/layout.tsx
  app/admin/members/page.tsx
  app/api/admin/member/route.ts
  app/api/auth/[...nextauth]/route.ts
  app/styret/page.tsx
  components/about/Member.tsx
  components/about/PastMembers.tsx
  components/about/SkeletonMember.tsx
  components/form/Checkbox.tsx
  components/form/OptionsBox.tsx
  components/form/Table.tsx
  components/form/TextInput.tsx
  lib/auth/apiChecks.ts
  lib/content.ts
  lib/prisma.ts
  lib/types.ts
  next.config.mjs
  package-lock.json
  package.json
  prisma/migrations/20241008133052_init/migration.sql
  prisma/migrations/20241008133355_member_model/migration.sql
  prisma/migrations/20241008133751_member_model_id/migration.sql
  prisma/migrations/20241008133914_add_year/migration.sql
  prisma/migrations/20241008144345_add_gender/migration.sql
  prisma/migrations/20241008144430_fdsdf/migration.sql
  prisma/migrations/20241008172303_fdsfs/migration.sql
  prisma/migrations/20241010164420_change_gender_to_enum/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  public/members/brinje.jpg
  public/members/byrkjeland.jpg
  public/members/duvara.jpg
  public/members/jakob.jpg
  public/members/maiken.jpg
  public/members/ouren.jpeg
  public/members/thea-karin-fladby.jpg
Labels: backend, frontend

#78 62 display past fond submissions
  app/admin/applications/page.tsx
  app/api/admin/application/route.ts
  app/api/admin/member/route.ts
  components/form/DateInput.tsx
  components/form/NumberInput.tsx
  lib/dateUtils.ts
  lib/types.ts
  lib/utilFunctions.ts
  prisma/migrations/20241013125758_djisfjod/migration.sql
  prisma/migrations/20241013141540_djisfjod/migration.sql
  prisma/migrations/20241013141804_djisfjod/migration.sql
  prisma/migrations/20241013141929_djisfjod/migration.sql
  prisma/migrations/20241014132220_dsoiijuho/migration.sql
  prisma/schema.prisma
Labels: backend, frontend

#80 79 frontend display past fond submissions
  app/admin/applications/page.tsx
  app/api/admin/application/route.ts
  app/soknad/page.tsx
  app/styret/page.tsx
  components/Submissions/ApplicationCard.tsx
  components/Submissions/FondApplications.tsx
  components/all/Error.tsx
  components/form/TextAreaInput.tsx
  lib/types.ts
  prisma/migrations/20241016164702_dfjdjoigjdr/migration.sql
  prisma/schema.prisma
Labels: frontend

#86 Remove "FAKE DATA"
  components/graphs/PerformanceDisplay.tsx
Labels: frontend

#88 Sort applications by desc date
  app/api/admin/application/route.ts
Labels: backend
