Repository appKom/penne, pull requests merged in 2024-09, with the labels that each got.

#59 Scrolldown icon is clickable
  src/components/home/ScrollDownIcon.tsx
  src/pages/home.tsx
Labels: enhancement

#65 Possible routing fix
  vercel.json
Labels: bug

#73 feat: added space over Brinjes head
  public/members/brinje.jpg
Labels: frontend

#71 Setup admin dashboard
  .env.local.template
  app/admin/applications/page.tsx
  app/admin/layout.tsx
  app/admin/members/page.tsx
  app/admin/page.tsx
  app/admin/portfolio/page.tsx
  app/api/auth/[...nextauth]/route.ts
  app/layout.tsx
  app/not-found.tsx
  components/all/Button.tsx
  components/all/Navbar.tsx
  lib/auth/SessionWrapper.tsx
  lib/auth/getUserGroups.ts
  lib/auth/next-auth.d.ts
  package-lock.json
  package.json
  public/not-found.svg
Labels: backend, frontend

#74 Admin dashboard design
  app/admin/page.tsx
Labels: styling
